### ISSUE TITLE
Crash to desktop due to ticking wolf entity

### ISSUE THREAD

**Issue by Darkona** [AlexModGuy/DomesticationInnovation#123]
This happened randomly and I have crashed a couple times with little to do for recovery. 

I have two wolves with tags.

To make matters short, the error is this:

`Caused by: java.lang.NullPointerException: Cannot read field "f_19853_" because "attacker" is null
	at com.github.alexthe668.domesticationinnovation.server.CommonProxy.onLivingHurt(CommonProxy.java:561) ~[domesticationinnovation-1.6.0-1.19.2.jar%23352!/:1.6.0-1.19.2]
	at com.github.alexthe668.domesticationinnovation.server.__CommonProxy_onLivingHurt_LivingAttackEvent.invoke(.dynamic) ~[domesticationinnovation-1.6.0-1.19.2.jar%23352!/:1.6.0-1.19.2]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:320) ~[forge-1.19.2-43.2.0-universal.jar%23468!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1025) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.world.entity.animal.Animal.m_6469_(Animal.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.world.entity.animal.Wolf.m_6469_(Wolf.java:294) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:333) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.world.entity.Mob.m_6075_(Mob.java:250) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:417) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2252) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:316) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.world.entity.animal.Wolf.m_8119_(Wolf.java:190) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:269) ~[client-1.19.2-20220805.130853-srg.jar%23463!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:61) ~[ItShallNotTick-1.0.11-build.35.jar%23386!/:1.0.11-build.35]`

The issue is that if something is attacked by a non-entity, there will be a crash. I think this happened when a create deployer that is auto-attacking hit a wolf with a tag. However cant get to the wolf in time before it crashes again.

**Comment by ChicknTurtle** [comment]
@AlexModGuy pls fix soon
