### ISSUE TITLE
Startup crash when installed with Project Save The Pets

### ISSUE THREAD

**Issue by xFirefalconx** [AlexModGuy/DomesticationInnovation#158]
Hi, I tried adding this mod to my modpack (working on an update). 
It however collides with a mod I am using already and I isolated it, both mods clash. I hope something can be done about it as I really like the features your mod introduces, but want to keep the features of Project Save The Pets. 

The error message:

```
mixin
pool-3-thread-1
@Redirect conflict. Skipping domesticationinnovation.mixins.json:PlayerMixin->@Redirect::di_onSweepAttack_isAlliedTo(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/entity/Entity;)Z with priority 1000, already redirected by projectsavethepets.mixins.json:PlayerEntityMixin->@Redirect::attack(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/entity/Entity;)Z with priority 1000
```
Full logs: [latest.log](https://github.com/AlexModGuy/DomesticationInnovation/files/12707024/latest.log)

Minecraft 1.18.2
Forge 40.2.4
citadel-1.11.3-1.18.2.jar
domesticationinnovation-1.4.2-1.18.2.jar
projectsavethepets-3.1.0-old.1.18+2022.10af157d70.forge.jar

There might other issues, I will further investigate, in case there is a possibility of an update. Thanks in advance.

**Comment by xFirefalconx** [comment]
https://gitlab.com/digitalcinnamonproductions/minecraft/projectsavethepets/-/issues/18

Posted the issue on their gitlab too

**Comment by xFirefalconx** [comment]
Additionally, if it's not possible to somehow pair these two mixins, can you maybe adapt their features to a certain point so dead pets (incl. modded ones) can be saved somewhere and revived if conditions are met? 
Project save the pets uses pieces of paper with the pet stats on it and lets you revive it by consuming a copper block upon right click. Maybe you find a solution that somehow works. 
I'm commenting since it's been months and no reaction yet so I don't know what's the current situation.

**Comment by RedFir3** [comment]
I also had this issue. In case my log contributes anything (put this through mclogs, so here's the link: https://mclo.gs/XATAxIh)

<details><summary>MultiMC Crash Log</summary>
<p>

MultiMC version: 0.7.0-3863


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [**.**.**.**]

textures.minecraft.net resolves to:
    [**.**.**.**]

api.mojang.com resolves to:
    [**.**.**.**]


Minecraft folder is:
C:/Users/********/Games/mmc-stable-win32/MultiMC/instances/1.20.1 Vanilla Brooder Plus1/.minecraft


Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe


Checking Java version...
Java is version 17.0.8, using 64-bit architecture, from Oracle Corporation.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/********/Games/mmc-stable-win32/MultiMC/instances/1.20.1 Vanilla Brooder Plus1/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.7/asm-9.7.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.7/asm-commons-9.7.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.7/asm-tree-9.7.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.7/asm-util-9.7.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.7/asm-analysis-9.7.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/eventbus/6.0.5/eventbus-6.0.5.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forgespi/7.0.1/forgespi-7.0.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/coremods/5.1.6/coremods-5.1.6.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/fmlloader/1.20.1-47.3.0/fmlloader-1.20.1-47.3.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/fmlearlydisplay/1.20.1-47.3.0/fmlearlydisplay-1.20.1-47.3.0.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] citadel-2.6.0-1.20.1.jar
  [✔️] domesticationinnovation-1.7.1-1.20.1.jar
  [✔️] projectsavethepets-4.0.1-alpha+2023.7fa0c6d61f.forge.jar

Params:
  --username DreagonessBree --version 1.20.1 --gameDir C:/Users/********/Games/mmc-stable-win32/MultiMC/instances/1.20.1 Vanilla Brooder Plus1/.minecraft --assetsDir C:/Users/********/Games/mmc-stable-win32/MultiMC/assets --assetIndex 5 --uuid <PROFILE ID> --accessToken ****************:**************** TOKEN> --userType msa --versionType release --launchTarget forgeclient --fml.forgeVersion 47.3.0 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx5120m, -Duser.language=en]


Minecraft process ID: 22752


Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-12-09 23:03:52,161 main WARN Advanced terminal features are not available in this environment
[23:03:52] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, DreagonessBree, --version, 1.20.1, --gameDir, C:/Users/********/Games/mmc-stable-win32/MultiMC/instances/1.20.1 Vanilla Brooder Plus1/.minecraft, --assetsDir, C:/Users/********/Games/mmc-stable-win32/MultiMC/assets, --assetIndex, 5, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, --width, 854, --height, 480]
[23:03:52] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[23:03:52] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[23:03:52] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[23:03:53] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[23:03:53] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/********/Games/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23122!/ Service=ModLauncher Env=CLIENT
[23:03:53] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 566.03, NVIDIA Corporation
[23:03:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\********\Games\mmc-stable-win32\MultiMC\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.0\fmlcore-1.20.1-47.3.0.jar is missing mods.toml file
[23:03:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\********\Games\mmc-stable-win32\MultiMC\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.0\javafmllanguage-1.20.1-47.3.0.jar is missing mods.toml file
[23:03:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\********\Games\mmc-stable-win32\MultiMC\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.0\lowcodelanguage-1.20.1-47.3.0.jar is missing mods.toml file
[23:03:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\********\Games\mmc-stable-win32\MultiMC\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.0\mclanguage-1.20.1-47.3.0.jar is missing mods.toml file
[23:03:53] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[23:03:55] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[23:03:55] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Users\********\Games\mmc-stable-win32\MultiMC\instances\1.20.1 Vanilla Brooder Plus1\.minecraft, --assetsDir, C:\Users\********\Games\mmc-stable-win32\MultiMC\assets, --uuid, <PROFILE ID>, --username, DreagonessBree, --assetIndex, 5, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[23:03:57] [main/WARN] [os.ut.pl.wi.PerfDataUtil/]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[23:03:57] [main/WARN] [os.ut.pl.wi.PerfCounterQueryHandler/]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[23:03:57] [main/WARN] [os.ut.pl.wi.PerfCounterQuery/]: Disabling further attempts to query Paging File.
[23:03:57] [main/WARN] [os.ut.pl.wi.WmiQueryHandler/]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[23:03:58] [pool-4-thread-1/WARN] [mixin/]: @Redirect conflict. Skipping domesticationinnovation.mixins.json:PlayerMixin->@Redirect::di_onSweepAttack_isAlliedTo(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/entity/Entity;)Z with priority 1000, already redirected by projectsavethepets.mixins.json:protection.Sweeping->@Redirect::preventAttack(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/entity/Entity;)Z with priority 1000
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 20 more
Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:32)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:151)
	... 28 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.registries.GameData.init(GameData.java:107)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.registries.GameData.<clinit>(GameData.java:93)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:429)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:409)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:121)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.lambda$main$0(Main.java:151)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector di_onSweepAttack_isAlliedTo(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/entity/Entity;)Z in domesticationinnovation.mixins.json:PlayerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap domesticationinnovation.refmap.json
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 25 more
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 09 Dec 2024 23:04:02 -0700

</p>
</details>
