### ISSUE TITLE
A spider ran into me and the game threw a fit

### ISSUE THREAD

**Issue by Artembelov** [AlexModGuy/DomesticationInnovation#68]
---- Minecraft Crash Report ----
// Uh... Did I do that?
 
Time: 8/20/22, 8:23 PM
Description: Unexpected error
 
java.lang.IllegalArgumentException: Can't find attribute null
	at net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22260_(AttributeSupplier.java:21) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22245_(AttributeSupplier.java:28) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.attributes.AttributeMap.m_22181_(AttributeMap.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_21133_(LivingEntity.java:1818) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:spoornarmorattributes-common.mixins.json:LivingEntityMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinLivingEntity,pl:mixin:APP:wyml.mixins.json:MixinLivingEntity,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:cgm.mixins.json:common.LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:oreberriesreplanted.mixins.json:LivingEntityAccessor,pl:mixin:APP:notenoughanimations.mixins.json:LivingEntityMixin,pl:mixin:APP:ecologics-common.mixins.json:LivingEntityMixin,pl:mixin:APP:brass_armory.mixin.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:APP:unionlib.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:biomemakeover-common.mixins.json:LivingEntityMixin,pl:mixin:APP:biomemakeover-common.mixins.json:LivingEntityMixin_Lootblock,pl:mixin:APP:biomemakeover-common.mixins.json:enchantment.LivingEntityMixin,pl:mixin:APP:biomemakeover-common.mixins.json:totem.LivingEntityMixin,pl:mixin:APP:wooledboots.mixins.json:LivingEntityEdits,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at com.stereowalker.unionlib.UnionLib.lambda$onModStartup$0(UnionLib.java:112) ~[UnionLib-1.18.2-7.2.0-Forge.jar%23281!/:7.2.0] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.getCriticalHit(ForgeHooks.java:1008) ~[forge-1.18.2-40.1.73-universal.jar%23295!/:?] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1100) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.PlayerEntityMixin,pl:mixin:APP:spoornarmorattributes-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinPlayerEntity,pl:mixin:APP:spoornweaponattributes-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:playerrevive.mixins.json:PlayerMixin,pl:mixin:APP:notenoughanimations.mixins.json:PlayerEntityMixin,pl:mixin:APP:backpacked.mixins.json:common.PlayerEntityMixin,pl:mixin:APP:brass_armory.mixin.json:PlayerMixin,pl:mixin:APP:domesticationinnovation.mixins.json:PlayerMixin,pl:mixin:APP:unionlib.mixins.json:PlayerMixin,pl:mixin:APP:biomemakeover-common.mixins.json:PlayerMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:taxfreelevels-forge.mixins.json:FlattenEnchantmentCostMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105223_(MultiPlayerGameMode.java:360) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_202354_(Minecraft.java:1503) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1848) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1669) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1020) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:664) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22260_(AttributeSupplier.java:21) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22245_(AttributeSupplier.java:28) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.attributes.AttributeMap.m_22181_(AttributeMap.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_21133_(LivingEntity.java:1818) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:spoornarmorattributes-common.mixins.json:LivingEntityMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinLivingEntity,pl:mixin:APP:wyml.mixins.json:MixinLivingEntity,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:cgm.mixins.json:common.LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:oreberriesreplanted.mixins.json:LivingEntityAccessor,pl:mixin:APP:notenoughanimations.mixins.json:LivingEntityMixin,pl:mixin:APP:ecologics-common.mixins.json:LivingEntityMixin,pl:mixin:APP:brass_armory.mixin.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:APP:unionlib.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:biomemakeover-common.mixins.json:LivingEntityMixin,pl:mixin:APP:biomemakeover-common.mixins.json:LivingEntityMixin_Lootblock,pl:mixin:APP:biomemakeover-common.mixins.json:enchantment.LivingEntityMixin,pl:mixin:APP:biomemakeover-common.mixins.json:totem.LivingEntityMixin,pl:mixin:APP:wooledboots.mixins.json:LivingEntityEdits,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at com.stereowalker.unionlib.UnionLib.lambda$onModStartup$0(UnionLib.java:112) ~[UnionLib-1.18.2-7.2.0-Forge.jar%23281!/:7.2.0] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.getCriticalHit(ForgeHooks.java:1008) ~[forge-1.18.2-40.1.73-universal.jar%23295!/:?] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1100) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.PlayerEntityMixin,pl:mixin:APP:spoornarmorattributes-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinPlayerEntity,pl:mixin:APP:spoornweaponattributes-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:playerrevive.mixins.json:PlayerMixin,pl:mixin:APP:notenoughanimations.mixins.json:PlayerEntityMixin,pl:mixin:APP:backpacked.mixins.json:common.PlayerEntityMixin,pl:mixin:APP:brass_armory.mixin.json:PlayerMixin,pl:mixin:APP:domesticationinnovation.mixins.json:PlayerMixin,pl:mixin:APP:unionlib.mixins.json:PlayerMixin,pl:mixin:APP:biomemakeover-common.mixins.json:PlayerMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:taxfreelevels-forge.mixins.json:FlattenEnchantmentCostMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105223_(MultiPlayerGameMode.java:360) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_202354_(Minecraft.java:1503) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1848) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['MentalTragedy'/133, l='ClientLevel', x=677.32, y=63.00, z=310.66]]
	Chunk stats: 1024, 318
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,106,0), Section: (at 0,10,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 16636 game time, 16636 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:flytre_lib.mixins.json:event.ClientWorldMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:unionlib.mixins.json:client.ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2261) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:686) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:flytre_lib.mixins.json:event.MinecraftClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23290!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by AlexModGuy** [comment]
>  at com.stereowalker.unionlib.UnionLib.lambda$onModStartup$0(UnionLib.java:112) ~[UnionLib-1.18.2-7.2.0-Forge.jar%23281!/:7.2.0] {re:mixin,re:classloading}
